stages:
  - test

test:
  stage: test
  script:
    - apt-get update -qq && apt-get install -y python3-pip python3 net-tools graphviz traceroute
    - pip3 install poetry
    - poetry install
    - cp ./install/config.test ./config.py
    - poetry run invoke install
    - poetry run invoke test


include:
  - template: Security/SAST.gitlab-ci.yml