version: "3.7"

services:
  bookmaker:
    build:
      context: .
      args:
        - BOOKMAKER_BOT_TOKEN=${BOOKMAKER_BOT_TOKEN}
        - BOOKMAKER_ADMIN=${BOOKMAKER_ADMIN}
        - BOOKMAKER_MDP=${BOOKMAKER_MDP}
        - RUGBY_API_KEY=${RUGBY_API_KEY}
    container_name: bookmaker
    volumes:
      - bookmaker-data:/app/ressources
      - bookmaker-log:/app/log
    environment:
      - BOOKMAKER_BOT_TOKEN=${BOOKMAKER_BOT_TOKEN}
      - BOOKMAKER_ADMIN=${BOOKMAKER_ADMIN}
      - BOOKMAKER_MDP=${BOOKMAKER_MDP}
      - RUGBY_API_KEY=${RUGBY_API_KEY}


volumes:
  bookmaker-data:
  bookmaker-log: